spring:
  application:
    name: taskify
  docker:
    compose:
      lifecycle-management: start_only
  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5434/railway}
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
vaadin:
  launch-browser: false
management:
  endpoints:
    web:
      exposure:
        include: health
